### ISSUE TITLE
Filter design

### ISSUE THREAD

**Issue by rubensmz** [sq5mjw/STM32F746G-DSP-Filter-Lab#1]
Hi, 

first of all I would like to thank your amazing job in this repository. I have been playing around with your code but I am unable to change the IIR filters.

How have you got those coefficients? I have tried to use MATLAB function `tf2sos` and deleted ones column. Nevertheless, although I have read thoroughly the CMSIS documentation I cannot find a solution. Could you tell me more about the filter design for implementing with `arm_biquad_cascade_df2T_f32()` function?

Thank you very much!

**Comment by sq5mjw** [comment]
Hi,
For filters I've used FIR/IIR tools from http://www.iowahills.com/8DownloadPage.html. IIR Filters coefs generated by these programs need to be changed sign(-) and order of some variables. For example output from IIR is (ony first structure block):

1.000000000000000000
-1.941978696337710810
0.959988771273521113
-0.020384435620409078
0.000000000000000000
0.020384435620409078

and arguments for arm_ function (first part of structure):

-0.020384435620409078,
0.000000000000000000,
0.020384435620409078,
-1.941978696337710810,
-0.959988771273521113,

As you can see "1" is omitted cos is always "1", and order of arguments is little changed. You may track based on above example what value is in what order for arm_ function.

For Matlab you have to check order of variables and signs as well. I don't have Matlab expirience.

regards,
Radek
